FROM node:14-alpine

COPY . /app
WORKDIR /app

RUN yarn install && yarn build

RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /root/.cache /root/.config /root/.npm /root/.yarn
EXPOSE 7776
CMD ["yarn" "start"]
