# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [14, 16]
        architecture: [x64]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        architecture: ${{ matrix.architecture }}
        check-latest: true
        cache: 'npm'
    - run: npx browserslist@latest --update-db && npm install
    - run: npm run build
      env:
        S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
        S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
        S3_DOWNLOAD_LINK_BASE: ${{ secrets.S3_DOWNLOAD_LINK_BASE }}
        ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}
    - run: npm install -g npm-run-all && npm run testall
